title: cake

api:
  port: 8081
  debug: true

logger:
  level: debug

env: LOCAL

authentication:
  api_keys:
    - ed8d0990-4994-412f-8170-8d2a657c8e8a

mysql:
  host: 10.50.69.14
  port: 30306
  username: root
  password: test1234
  database_name: cake

sqlite:
  path: "./"

database:
  db_type: "mysql"
  max_idle_conns: 10
  max_open_conns: 10
  conn_max_lifetime: 5
  conn_max_idle_time: 5
  enable_auto_migrate: true
